version: '3.9'
services:
  sh: &base
    image: node:14-alpine
    volumes:
      - .:/opt/code
    working_dir: /opt/code
    command: sh

  install:
    <<: *base
    command: npm install

  compile:
    <<: *base
    command: npm run compile