name: ci
on:
  push:
    branches-ignore:
      - main

jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm test

      - name: Compile
        run: npm run compile
